stages:
- build
- test 

build:
  stage: build
  script:
    - run:
      name: chmod permissions
      command: chmod +x ./gradlew
    - ./gradlew build -x test
    - ./gradlew.bat --stop 
test:
  stage: test
  script:
    - ./gradlew test
    - ./gradlew.bat --stop
