image: gradle:alpine

stages:
- build
- test

build:
  stage: build
  script:
    - cd hpf-api   
    - ./gradlew build -x test
    - ./gradlew.bat --stop 
test:
  stage: test
  script:
    - cd hpf-api 
    - ./gradlew test
    - ./gradlew.bat --stop
sonarqube-check:
  stage: test
  variables:
    SONAR_TOKEN: "bc9cfe1f984968e7844311eeb3dcbcdff9b34a70"
    SONAR_HOST_URL: "http://localhost:9000"
    GIT_DEPTH: 0
  script: 
    - cd hpf-api
    – gradle sonarqube -Dsonar.qualitygate.wait=true
  allow_failure: true
  only:
    - merge_requests
    - master


