stages:
  - build
  - test

build:
  stage: build
  script:
    - chmod +x gradlew
    - ./gradlew build -x test
    - .gradlew.bat --stop

test:
  stage: test
  script:
    - ./gradlew test
    - ./gradlew.bat -stop

after script:
  - echo "End CI:"
  - exit