stages:
- build
- test 

build:
  stage: build
  script:
    - ./gradlew build -x test
    - chmod +x gradlew
    - ./gradlew.bat --stop 
test:
  stage: test
  script:
    - ./gradlew test
    - ./gradlew.bat --stop
