before_script:
  - $env:JAVA_HOME = "C:\Users\pro4erb\Documents\jdk-17.0.2"
  - $env:Path = $env:JAVA_HOME + '/bin;' + $env:Path

stages:
  - build
  - test
  - sonar
  - cypress

build:
  stage: build
  script:
    - cd hpf-api
    - ./gradlew clean --stacktrace
    - ./gradlew assemble --stacktrace

test:
  stage: test
  script:
    - cd hpf-api
    - ./gradlew test --stacktrace

sonar:
  stage: sonar
  only:
    - main
  allow_failure: true
  script:
    - cd hpf-api
    - ./gradlew sonarqube --stacktrace

cypress:
  stage: cypress
  script:
    - cd hpf-react
    - cypress run


